version: '3.8'
services:
    
    web:
        build: .
        container_name: rails_dev
        command: bundle exec rails s -p 3000 -b '0.0.0.0'
        ports:
            - "3000:3000"
        volumes:
            - .:/app/
            - /node_modules:/app/node_modules/
            - cache:/cache # Added to support Windows 10 Docker
        environment:
            - SPROCKETS_CACHE=/cache # Added to support Windows 10 Docker

volumes:
    cache: