version: '3.5'
services:
    
    ruby_dev:
        build: .
        container_name: ruby_dev
        ports:
            - "3000:3000"
        volumes:
            - ./:/home/app
            - ./node_modules:/home/app/node_modules
