name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Ruby
      - uses: ruby/setup-ruby@v1.46.0
        with: 
          ruby-version: 2.7.0

      - name: Install Dependencies
      - run: |
          gem install bundler

      - name: Install Gems
      - run: |
          bundle install

      - name: Prepare Database
      - run: |
          bundle exec rails db:migrate

      - name: Run Tests
      - run: |
          bundle exec rails test
